source 'https://rubygems.org'
gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'rake'
gem 'facebook-messenger'
gem 'httparty'
gem 'dotenv'
gem 'json'
gem 'wit'
gem 'whenever'
gem 'wikipedia_rest_client'
gem 'mysql2'